# Generated by Django 3.0.7 on 2020-06-13 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Symptom_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom1', models.CharField(blank=True, max_length=256)),
                ('symptom2', models.CharField(blank=True, max_length=256)),
                ('symptom3', models.CharField(blank=True, max_length=256)),
                ('symptom4', models.CharField(blank=True, max_length=256)),
                ('symptom5', models.CharField(blank=True, max_length=256)),
                ('symptom6', models.CharField(blank=True, max_length=256)),
                ('symptom7', models.CharField(blank=True, max_length=256)),
            ],
        ),
    ]
